openapi: 3.0.3
info:
  title: Banking app
  description: A simple banking app api
  version: 0.0.0
servers:
  - url: 'https'
paths:
  /ping:
    get:
      tags:
        - Health
      responses:
        200:
          description: OK
          content:
            plain/text:
              schema:
                type: string
              example: pong

components:
  parameters:
    ## Common path with /{id} param
    idPath:
      name: id
      in: path
      schema:
        type: string

  responses:
    404:
      description: resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseErrorPayload'
          example:
            status: 404
            message: resource not found
    500:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseErrorPayload'
          example:
            status: 500
            message: cannot perform operations now

  schemas:
    ResponseErrorPayload:
      description: a blueprint for the response
      type: object
      properties:
        status:
          type: number
          example: 404
        message:
          type: string
