openapi: 3.0.3
info:
  title: Banking app
  description: A simple banking app api
  version: 0.0.0
servers:
  - url: 'https'
paths:
  /ping:
    get:
      tags:
        - Health
      responses:
        200:
          description: OK
          content:
            plain/text:
              schema:
                type: string
              example: pong
  /account:
    get:
      tags:
        - Account
      operationId: getAllAccounts
      summary: get a list of all accounts
      responses:
        200:
          description: account list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAccountDto'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'
    post:
      tags:
        - Account
      operationId: createAccount
      summary: create a bank account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpSetAccountDto'
      responses:
        201:
          description: created account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountDto'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /account/{id}:
    get:
      tags:
        - Account
      operationId: getAccountById
      summary: get account by an id
      responses:
        200:
          description: account data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountDto'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - Account
      operationId: updateAccountById
      summary: update account by an id
      parameters:
        - $ref: '#/components/parameters/idPath'
      responses:
        200:
          description: updated account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountDto'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

components:
  parameters:
    ## Common path with /{id} param
    idPath:
      name: id
      in: path
      schema:
        type: string

  responses:
    404:
      description: resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseErrorPayload'
          example:
            status: 404
            message: resource not found
    500:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseErrorPayload'
          example:
            status: 500
            message: cannot perform operations now

  schemas:
    ResponseErrorPayload:
      description: a blueprint for the response
      type: object
      properties:
        status:
          type: number
          example: 404
        message:
          type: string
    UpSetAccountDto:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        birthdate:
          type: string
          format: date
          description: age should be greater than 21
        netMonthSalary:
          type: number
          format: double
        accountNumber:
          type: string
      required:
        - firstname
        - lastname
        - birthdate
        - netMonthSalary
        - accountNumber
    GetAccountDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/UpSetAccountDto'
      properties:
        id:
          type: string
